---
apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
  name: jet-apigeeprov-config
  labels:
    app: crossplane-apigeeprov
spec:
  image: crossplane/apigeeprov-controller:v0.1.0
  args: ["-d"]
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: crossplane-apigeeprov
spec:
  package: crossplane/apigeeprov:v0.1.0
  controllerConfigRef:
    name: jet-apigeeprov-config
